version: '3' # specify docker-compose version
# Define the services/containers to be run
services:
  backend: #name of the second service
    build: . # specify the directory of the Dockerfile
    ports:
      - "3000:3000" #specify ports forewarding
    container_name: back-container
    restart: always
    links:
      - mongo # link this service to the database service
  frontend: #name of the first service
    build: client # specify the directory of the Dockerfile
    ports:
      - "4200:4200" # specify port forewarding
    container_name: front-container
    restart: always
  mongo: # name of the third service
    container_name: mongo
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=dmsdb
    ports:
      - "27018:27017"